[package]
name = "commoncrypto-sys"
version = "0.1.0"
authors = ["Mark Lee"]
description = "FFI bindings to Mac OS X's CommonCrypto library"
documentation = "https://docs.rs/commoncrypto-sys"
repository = "https://github.com/malept/rust-commoncrypto"
readme = "README.md"
keywords = ["crypto", "hash", "digest", "osx", "commoncrypto"]
license = "MIT"

[features]
lint = ["clippy"]

[dependencies]
hex = "0.2"
libc = "0.2"

clippy = { version = "0.0", optional = true }
